# ========= Copyright 2023-2024 @ CAMEL-AI.org. All Rights Reserved. =========
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========= Copyright 2023-2024 @ CAMEL-AI.org. All Rights Reserved. =========

# Enables postponed evaluation of annotations (for string-based type hints)
from __future__ import annotations

import logging
import json
import time
from dataclasses import asdict
from typing import Any, ClassVar, Dict
from enum import Enum
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field

from camel.messages import BaseMessage, FunctionCallingMessage, OpenAIMessage
from camel.types import OpenAIBackendRole, RoleType
from camel.storages.key_value_storages.json import CamelJSONEncoder


class MemoryRecord(BaseModel):
    r"""The basic message storing unit in the CAMEL memory system.

    Attributes:
        message (BaseMessage): The main content of the record.
        role_at_backend (OpenAIBackendRole): An enumeration value representing
            the role this message played at the OpenAI backend. Note that this
            value is different from the :obj:`RoleType` used in the CAMEL role
            playing system.
        uuid (UUID, optional): A universally unique identifier for this record.
            This is used to uniquely identify this record in the memory system.
            If not given, it will be assigned with a random UUID.
        extra_info (Dict[str, str], optional): A dictionary of additional
            key-value pairs that provide more information. If not given, it
            will be an empty `Dict`.
        timestamp (float, optional): The timestamp when the record was created.
        agent_id (str): The identifier of the agent associated with this
            memory.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    message: BaseMessage
    role_at_backend: OpenAIBackendRole
    uuid: UUID = Field(default_factory=uuid4)
    extra_info: Dict[str, str] = Field(default_factory=dict)
    timestamp: float = Field(
        default_factory=lambda: time.time_ns()
        / 1_000_000_000  # Nanosecond precision
    )
    agent_id: str = Field(default="")

    _MESSAGE_TYPES: ClassVar[dict] = {
        "BaseMessage": BaseMessage,
        "FunctionCallingMessage": FunctionCallingMessage,
    }

    @classmethod
    def from_dict(cls, record_dict: Dict[str, Any]) -> "MemoryRecord":
        r"""Reconstruct a :obj:`MemoryRecord` from the input dict.

        Args:
            record_dict(Dict[str, Any]): A dict generated by :meth:`to_dict`.
        """
        # Decode legacy enum markers recursively (e.g., {"__enum__": "RoleType.USER"})
        def _decode_legacy_enums(obj: Any) -> Any:
            if isinstance(obj, dict):
                if "__enum__" in obj:
                    try:
                        name, member = obj["__enum__"].split(".")
                        enum_cls = CamelJSONEncoder.CAMEL_ENUMS.get(name)
                        if enum_cls is not None:
                            return getattr(enum_cls, member)
                    except Exception as _e:
                        logging.info(f"MemoryRecord Exception {_e} when converting {obj} to Enum")
                        return obj
                return {k: _decode_legacy_enums(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [_decode_legacy_enums(v) for v in obj]
            return obj

        record_dict = _decode_legacy_enums(record_dict)

        message_cls = cls._MESSAGE_TYPES[record_dict["message"]["__class__"]]
        kwargs: Dict = record_dict["message"].copy()
        kwargs.pop("__class__")
        # Restore enums expected by BaseMessage
        if "role_type" in kwargs and isinstance(kwargs["role_type"], str):
            try:
                kwargs["role_type"] = RoleType(kwargs["role_type"])
            except Exception as _e:
                logging.info(f"Exception {_e} when converting role_type to RoleType")
                pass
        reconstructed_message = message_cls(**kwargs)
        return cls(
            uuid=UUID(record_dict["uuid"]),
            message=reconstructed_message,
            role_at_backend=(
                OpenAIBackendRole(record_dict["role_at_backend"]) if isinstance(record_dict["role_at_backend"], str)
                else record_dict["role_at_backend"]
            ),
            extra_info=record_dict["extra_info"],
            timestamp=record_dict["timestamp"],
            agent_id=record_dict["agent_id"],
        )

    def to_dict(self) -> Dict[str, Any]:
        r"""Convert the :obj:`MemoryRecord` to a JSON-serializable dict.

        Enum 序列化规则以 `JsonStorage` 的 Encoder 为主：使用
        CamelJSONEncoder 将 Enum 编码为 {"__enum__": "Name.Member"} 的
        形式，保证 Redis/文件 两种存储一致，并由 from_dict 做统一还原。
        """
        message_dict: Dict[str, Any] = {
            "__class__": self.message.__class__.__name__,
            **asdict(self.message),
        }

        # 构建原始 dict（允许携带 Enum 对象）
        raw: Dict[str, Any] = {
            "uuid": str(self.uuid),
            "message": message_dict,
            "role_at_backend": self.role_at_backend,
            "extra_info": self.extra_info,
            "timestamp": self.timestamp,
            "agent_id": self.agent_id,
        }

        # 通过 JSON round-trip 使用 CamelJSONEncoder 进行统一的枚举编码
        encoded_str = json.dumps(raw, ensure_ascii=False, cls=CamelJSONEncoder)
        out: Dict[str, Any] = json.loads(encoded_str)
        return out

    def to_openai_message(self) -> OpenAIMessage:
        r"""Converts the record to an :obj:`OpenAIMessage` object."""
        return self.message.to_openai_message(self.role_at_backend)


class ContextRecord(BaseModel):
    r"""The result of memory retrieving."""

    memory_record: MemoryRecord
    score: float
    timestamp: float = Field(
        default_factory=lambda: time.time_ns()
        / 1_000_000_000  # Nanosecond precision
    )
